name: Re-enable workflow
on:
  schedule:
    - cron: 35 17 12 */1 *
  workflow_dispatch:

jobs:
  re-enable:
    runs-on: ubuntu-latest
    steps:
      - run: >
          curl -X PUT -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              https://api.github.com/repos/${{ env.GITHUB_REPOSITORY }}/actions/workflows/cron.yml/enable
